# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e665289ac5afe99499559e0ac9a707d1da5b93c6748b3435090a411d225fe59dc4c6c86fb54c247a356828728bc9ec9f5c52f1eea50647f93837874f61bdf758

test:
  secret_key_base: f465ec90f5254e25aa8424285dcf2b06177fe0324187f741960f88345fb75584db16986f748315b785e94943aeb4aa2d6e29f0aee8cbc3c88e0c34285b2cad9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
